modLoader="javafml"
loaderVersion="[37,)"
license="LGPL"
issueTrackerURL="https://github.com/Drullkus/Shield-Parry/issues"
[[mods]]
modId="parry"
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
# ${file.jarVersion} will substitute the value of the Implementation-Version as read from the mod's JAR file metadata
# see the associated build.gradle script for how to populate this completely automatically during a build
version="${file.jarVersion}"
displayName="Shield Parry"
# A URL to query for updates for this mod. See the JSON update specification https://docs.minecraftforge.net/en/latest/misc/updatechecker/
updateJSONURL="https://raw.githubusercontent.com/Drullkus/Shield-Parry/1.17.x/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/parry"
logoFile="parry.png"
credits="Inspired by Breath of the Wild's parrying and all of the parrying fanatics out there"
authors="Drullkus"
description='''
Parry Projectiles with your shield!

Twilight Forest is awesome, you should play that mod too! :)
'''
[[dependencies.parry]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.parry]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
